Added startup script

diff --git a/systemctl b/systemctl
--- a/systemctl
+++ b/systemctl
@@ -3,7 +3,29 @@
 # lower vars:     in local function
 # camelcase vars: systemd params var
 
-
+if ! grep -q fake_systemctl_start ~/.bashrc; then
+    echo '
+function fake_systemctl_start() {
+    echo "====   Fake Systemd Startup    ===="
+    for service in /etc/systemd/system/multi-user.target.wants/*;
+    do
+        first=${service##*/}
+        if [[ $first == *service ]]; then
+            name=${first/.service}
+            echo -n "Starting $name... "
+            systemctl start $name &>> /var/log/fake_systemd.log
+            if (( $? == 0 )); then
+                echo "OK"
+            else
+                echo "FAIL"
+            fi
+        fi
+    done
+    echo "==== Done Fake Systemd Startup ===="
+}
+fake_systemctl_start
+' >> ~/.bashrc
+fi
 if [ ! -d /pids ]; then
     mkdir /pids
 fi
